version: 0.2

phases:
  build:
    commands:
      - echo "Building AWS HTML files"
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
